import {bindLongPress} from './gestures.js';
import {ATTRS,SKILLS,CONDITIONS,initial} from './data.js';
import {derived,mod,signed,skillBonus,saveBonus,attackStats,canAttack,d20,rollDice,effectiveMode,exportData,importData,validateState,clone} from './engine.js';
import {getState,dispatch,canUndo,undoLast,updateContent,getWarning,replaceState,restoreBackup,hasBackup,rawSave} from './storage.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons=['ki','vitalite','carapace','poing','baton','griffes','flechettes','main-ouverte','meditation','deplacement','reaction','jets','social','journal','inventaire','ceinture','brassards','chaussons','calebasse','repos'];
const icon=(name,cls='')=>`<img class="icon ${cls}" src="./assets/icons/${icons.includes(name)?name:'inventaire'}.png" alt="" draggable="false">`;
const btn=(label,cmd,cls='',disabled=false)=>`<button class="${cls}" data-cmd="${esc(cmd)}" ${disabled?'disabled':''}>${label}</button>`;
const options=(arr,current)=>arr.map(([value,label])=>`<option value="${esc(value)}" ${value===current?'selected':''}>${esc(label)}</option>`).join('');
const field=(label,id,value,type='text',extra='')=>`<label>${label}<input id="${id}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const check=(label,id,on=false)=>`<label class="check"><input id="${id}" type="checkbox" ${on?'checked':''}>${label}</label>`;
const num=(id)=>Number($('#'+id).value);
let view='home',combatTab='attacks',socialTab='skills',rollMode='normal',invQuery='',invType='',noteQuery='',noteCategory='',trash=false,offlineReady=false,toastTimer,previousFocus,pending=null,modalVersion=0;
const sessionId=crypto.randomUUID();
const sheet=$('#sheet');
function show(title,body,kicker='KARU · COMPAGNON'){modalVersion++;if(!sheet.open){previousFocus=document.activeElement;sheet.showModal();document.body.classList.add('modal-open');}$('#sheet-title').textContent=title;$('#sheet-kicker').textContent=kicker;$('#sheet-body').innerHTML=body+'<div id="modal-error" class="modal-error" role="alert"></div>';sheet.scrollTop=0;}
function close(){const cmd=previousFocus?.dataset?.cmd;sheet.close();document.body.classList.remove('modal-open');pending=null;render();const focusTarget=[...document.querySelectorAll('[data-cmd]')].find(el=>el.dataset.cmd===cmd);(focusTarget||document.querySelector('#main button'))?.focus?.({preventScroll:true});}
$('#close-sheet').onclick=close;sheet.addEventListener('cancel',e=>{e.preventDefault();close()});sheet.addEventListener('click',e=>{if(e.target===sheet){const r=sheet.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),5000);}
function fail(error){if(sheet.open&&$('#modal-error'))$('#modal-error').textContent=error.message||String(error);else toast(error.message||String(error));}
function commit(e,{stay=false}={}){const buttons=[...sheet.querySelectorAll('button')].filter(b=>!b.disabled);buttons.forEach(b=>b.disabled=true);try{const message=dispatch({...e,transactionId:`${sessionId}:${modalVersion}:${e.type}:${e.id||''}`});$('#close-sheet').disabled=false;if(!stay)close();render();toast(message);return true}catch(err){buttons.forEach(b=>b.disabled=false);fail(err);return false}}
function heading(title,sub,action=''){return `<div class="page-heading"><div><span class="eyebrow">LE CHEMIN DE KARU</span><h2>${title}</h2><p>${sub}</p></div>${action}</div>`;}
function card(title,sub,ic,cmd,detailId,tail='',featured=false){return `<div class="action-card ${featured?'featured':''}"><button class="action-main" data-cmd="${esc(cmd)}" ${detailId?`data-detail="${esc(detailId)}"`:''}>${icon(ic)}<span class="text"><strong>${esc(title)}</strong><small>${esc(sub)}</small></span>${tail?`<em>${tail}</em>`:''}</button>${detailId?`<button class="detail-button" data-cmd="detail|${esc(detailId)}" aria-label="Détails : ${esc(title)}">i</button>`:''}</div>`;}
function render(){const s=getState(),d=derived(s);document.body.dataset.view=view;document.body.classList.toggle('contrast',s.settings.contrast);document.body.classList.toggle('reduce-motion',s.settings.reduceMotion);
 $('#header').innerHTML=`<div class="topline"><div class="brand">${icon('carapace')}<div><b>${esc(s.character.name)}</b><small style="display:block">${view==='home'?'LA VOIE DE LA MAIN OUVERTE':'Moine '+s.character.level+' · Grand-Père Coquille'}</small></div></div><div class="row"><span class="offline">${offlineReady?'Hors ligne prêt':navigator.onLine?'Local · sauvegardé':'Hors connexion'}</span>${btn('<svg viewBox="0 0 24 24"><path d="M4 7h16M4 17h16M8 4v6m8 4v6"/></svg>','settings','icon-button')}</div></div>${view!=='home'?`<div class="status">${btn(`${icon('vitalite')} <b>${s.resources.hp}<small style="display:inline"> / ${d.maxHp}</small></b><small>POINTS DE VIE</small><div class="hp-meter"><i style="width:${s.resources.hp/d.maxHp*100}%"></i></div>`,'health')}${btn(`<b>${s.resources.tempHp}</b><small>PV TEMP.</small>`,'health')}${btn(`${icon('carapace')} <b>${d.ac}</b><small>${s.shell?'EN CARAPACE':'ARMURE'}</small>`,'detail|natural')}${btn(`${icon('ki')} <b>${s.resources.ki}</b><small>KI / ${s.character.maxKi}</small>`,'resources')}</div>`:''}`;
 $('#header [data-cmd=settings]').setAttribute('aria-label','Réglages et sauvegardes');
 $('#storage-warning').textContent=getWarning();
 const tabs=[['home','Accueil','carapace'],['combat','Combat','poing'],['social','Social','social'],['journal','Journal','journal']];
 $('#dock').innerHTML=tabs.map(([id,name,ic])=>`<button data-cmd="nav|${id}" class="${view===id?'active':''}" ${view===id?'aria-current="page"':''}>${icon(ic)}<span>${name}</span></button>`).join('');
 $('#main').innerHTML=view==='home'?home(s):view==='combat'?combat(s,d):view==='social'?social(s,d):journal(s);
 if(view==='social'&&socialTab==='inventory'){$('#inventory-search').addEventListener('input',e=>{invQuery=e.target.value;renderInventory()});$('#inventory-filter').onchange=e=>{invType=e.target.value;renderInventory()};renderInventory();}
 if(view==='journal'){$('#note-search').oninput=e=>{noteQuery=e.target.value;renderNotes()};$('#category-filter').onchange=e=>{noteCategory=e.target.value;renderNotes()};renderNotes();}
}
function home(s){return `<section class="home"><div class="home-heading"><span class="eyebrow">OBSERVER · COMPRENDRE · PROTÉGER</span><h1>${esc(s.character.name.toUpperCase())}</h1><p>${esc(s.character.subtitle)}</p></div><div class="home-space"></div><div class="home-menu">${[['combat','Combat','Entrer dans le mouvement','poing'],['social','Social','Explorer, échanger, s’équiper','social'],['journal','Journal','Garder la trace du chemin','journal']].map(([id,name,sub,ic])=>`<button class="portal" data-cmd="nav|${id}">${icon(ic)}<span><strong>${name}</strong><small>${sub}</small></span><span class="arrow">›</span></button>`).join('')}</div><p class="home-footer">${s.resources.hp} PV · ${s.resources.ki} ki · Tour ${s.turn.number}${s.updatedAt?' · Dernière activité '+new Date(s.updatedAt).toLocaleDateString('fr-FR'):''}<br>Un pas après l’autre, le monde s’apaise.</p></section>`;}
function combat(s,d){const t=s.turn;return `${heading('Le calme avant le geste',t.phase==='active'?'À votre tour. Choisissez votre intention.':'Entre deux tours. Gardez votre réaction en vue.',`<span class="turn-no">${t.number}</span>`)}<div class="combat-layout"><section><div class="panel"><div class="panel-head"><span class="eyebrow">VOTRE TOUR</span>${btn('États'+(s.conditions.length?' · '+s.conditions.length:''),'conditions','pill')}</div><div class="economy">${[['action','Action',t.attacksLeft?`${t.attacksLeft} attaque restante`:t.action?'utilisée':'disponible'],['bonus','Bonus',t.flurryLeft?`${t.flurryLeft} frappe restante`:t.bonus?'utilisée':'disponible'],['reaction','Réaction',s.shell?'interdite':t.reaction?'utilisée':'disponible']].map(([key,name,status])=>`<div class="econ ${t[key]?'spent':''}"><b>${name}</b><small>${status}</small></div>`).join('')}</div><div class="ki-row"><div class="ki-dots" aria-label="${s.resources.ki} points de ki sur ${s.character.maxKi}">${Array.from({length:Math.min(20,s.character.maxKi)},(_,i)=>`<span class="${i<s.resources.ki?'on':''}"></span>`).join('')}</div>${btn('Repos','rest','pill')}</div><div class="pills">${btn(`${d.moveLeft.toLocaleString('fr-FR')} m restants`,'movement','pill')}${btn(`DD ${d.dc}`,'detail|ki','pill')}${s.conditions.map(c=>btn(esc(c),'conditions','pill')).join('')}</div></div>
 ${s.resources.hp===0?`<div class="panel"><h3 class="danger-text">${s.resources.dead?'Karu est mort':s.resources.stable?'Stabilisé · 0 PV':'Karu est inconscient'}</h3><p>${s.resources.success} réussites · ${s.resources.failure} échecs</p><div class="row grow">${btn('Jet de mort','death','primary',s.resources.dead||s.resources.stable)}${btn('Stabiliser','stabilize','',s.resources.dead||s.resources.stable)}</div></div>`:''}
 ${s.shell?`<div class="callout">Dans la carapace : CA ${d.ac}, aucun mouvement ni réaction. Seule la sortie en action bonus est disponible.</div>${card('Sortir de la carapace','Sortie normale ou propriété de ceinture','carapace','exit','shell')}`:''}
 ${s.lastHit?`<div class="panel"><span class="eyebrow">APRÈS LA TOUCHE · ${esc(s.lastHit.target)}</span><p>Ajouter un effet à cette attaque.</p><div class="grid2">${s.lastHit.melee?btn('Étourdissante · 1 ki','stun','',s.lastHit.stunUsed):''}${s.lastHit.flurry?btn('Main Ouverte','open','',s.lastHit.openUsed):''}</div></div>`:''}
 ${s.returnReady?card('Renvoyer le projectile','Immédiatement · même réaction · 1 ki','reaction','return','deflect'):''}
 <div class="bottom-actions">${btn('Annuler','undo','quiet',!canUndo())}${btn(t.phase==='active'?'Terminer mon tour':'Commencer mon tour',t.phase==='active'?'end-turn':'start-turn','primary')}</div><div class="toolbar">${btn('Historique','history')}${btn('Ajustement MJ','adjust')}</div>
 ${s.effects.length?`<div class="panel"><span class="eyebrow">EFFETS SUIVIS</span>${s.effects.map(e=>`<div class="log-entry"><div class="row end"><b>${esc(e.target)} · ${esc(e.name)}</b>${btn('Retirer','remove-effect|'+e.id,'pill')}</div><small>${e.boundary==='manual'?'Retrait manuel, selon la situation':(e.boundary==='end'?'Fin':'Début')+' du tour '+e.turn}</small></div>`).join('')}</div>`:''}</section><section>
 <div class="tabs" aria-label="Options de combat">${[['attacks','Attaques'],['techniques','Techniques'],['reactions','Réactions'],['saves','Jets']].map(([id,name])=>btn(name,'combat-tab|'+id,combatTab===id?'selected':'')).join('')}</div>
 ${combatTab==='attacks'?attackList(s):combatTab==='techniques'?techniqueList(s):combatTab==='reactions'?reactionList(s):saveList(s)}
 </section></div>`;}
function attackList(s){return `<p class="muted" style="font-size:12px;margin:8px 0 12px">Un toucher pour le jet · appui long pour les détails.</p>${Object.entries(s.attacks).filter(([id])=>!id.startsWith('_')).map(([id])=>{const a=attackStats(s,id);return card(a.name,`1d${a.die} ${signed(a.damageMod)} ${a.type}${a.melee?' · 1,5 m':' · 6/18 m'}`,a.icon,'attack|'+id+'|action','attack:'+id,signed(a.bonus),id==='staff2')}).join('')}
 ${s.turn.attacksLeft?btn('Terminer l’action Attaquer sans la dernière attaque','forfeit','quiet'):''}<p class="section-label">En action bonus</p>${card('Arts martiaux','Une frappe gratuite après une attaque admissible','poing','attack|unarmed|arts','arts')}${card(s.turn.flurryLeft?'Rafale · dernière frappe':'Rafale de coups',s.turn.flurryLeft?'Ki déjà dépensé · une frappe restante':'Deux frappes · 1 ki · après l’action Attaquer','main-ouverte','attack|unarmed|flurry','flurry')}`;}
function techniqueList(s){return [['Défense patiente','Esquiver · bonus · 1 ki','meditation','ability|patient','patient'],['Déplacement aérien','Foncer ou se désengager · bonus · 1 ki','deplacement','wind','wind'],['Défense de carapace','Se protéger · action · CA +4','carapace','ability|shell','shell'],['Intégrité physique',`${s.character.level*s.character.rules.wholeMultiplier} PV · action · ${s.resources.whole?'disponible':'épuisée'}`,'vitalite','ability|whole','whole'],['Quiétude de l’esprit','Mettre fin à charme ou peur · action','meditation','still','still']].map(a=>card(...a)).join('')+`<p class="section-label">Actions courantes</p><div class="grid2">${[['Foncer','dash'],['Esquiver','dodge'],['Se désengager','disengage'],['Aider','help'],['Se cacher','hide'],['Chercher','search'],['Préparer une action','ready'],['Utiliser un objet','object']].map(([label,id])=>btn(label,`common|${id}|${label}`)).join('')}</div><p class="section-label">Traits et maîtrise</p><div class="grid2">${['ki','empowered','breath','natural','movement','survival'].map(k=>btn(esc(s.details[k].name),'detail|'+k)).join('')}</div>`;}
function reactionList(s){return `${card('Parade de projectiles','Réduction 1d10 + '+(s.character.level+mod(s.character.stats.dex)),'reaction','deflect','deflect')}${card('Chute ralentie','Réduction '+s.character.level*s.character.rules.fallMultiplier+' dégâts de chute','deplacement','fall','fall')}${card('Attaque d’opportunité','Une attaque au corps à corps · réaction','poing','opportunity','opportunity')}${card('Esquive instinctive','Effet DEX pour moitié uniquement · passif','meditation','evasion','evasion')}<div class="callout">La réaction revient au début de votre prochain tour. Les déclencheurs sont confirmés avec le MJ.</div>`;}
function saveList(s){return `${card('Initiative','Dextérité · ordre de combat','jets','roll|initiative|dex','',signed(mod(s.character.stats.dex)))}<p class="section-label">Jets de sauvegarde</p><div class="skills">${Object.entries(ATTRS).map(([k,name])=>btn(`<span>${name}<small>${s.character.saves[k]?'MAÎTRISÉ':'SAUVEGARDE'}</small></span><b>${signed(saveBonus(s,k))}</b>`,'roll|save|'+k,'skill')).join('')}</div><p class="section-label">Dés libres</p>${btn('Lancer des dés personnalisés','free-dice','quiet')}`;}
function social(s,d){return heading('Au fil du chemin','Compétences, rencontres et affaires de voyage.')+`<div class="tabs">${btn('Compétences','social-tab|skills',socialTab==='skills'?'selected':'')}${btn('Inventaire','social-tab|inventory',socialTab==='inventory'?'selected':'')}</div>`+(socialTab==='skills'?`<div class="row end"><span class="pill">Perception passive ${d.passive}</span><span class="muted" style="font-size:11px">18 compétences · toutes accessibles</span></div><div class="skills" style="margin-top:12px">${SKILLS.map(([id,name,attr])=>btn(`<span>${name}<small>${ATTRS[attr]}${s.character.skills[id].proficiency?' · MAÎTRISE':''}</small></span><b>${signed(skillBonus(s,id))}</b>`,'roll|skill|'+id,'skill '+(s.character.skills[id].proficiency?'trained':''))).join('')}</div><p class="section-label">Caractéristiques</p><div class="skills">${Object.entries(ATTRS).map(([k,name])=>btn(`<span>${name}<small>SCORE ${s.character.stats[k]}</small></span><b>${signed(mod(s.character.stats[k]))}</b>`,'roll|check|'+k,'skill')).join('')}</div><div class="panel"><h3>Outils & langues</h3><div class="toolbar">${s.character.tools.map((tool,i)=>btn(esc(tool),'tool|'+i)).join('')}</div><p class="muted">${esc(s.character.languages)}</p></div>`:`<div class="panel"><div class="row end"><div><span class="eyebrow">HARMONISATIONS</span><h3>${s.items.filter(i=>i.attuned&&i.quantity>0).length} / 3 liens actifs</h3></div>${btn('Bourse · '+s.coins.po+' po','coins')}</div><div class="pills">${s.items.filter(i=>i.equipped&&i.quantity>0&&i.requiresAttunement).map(i=>`<span class="pill">${esc(i.name)}</span>`).join('')}</div></div><div class="row"><input class="search" id="inventory-search" placeholder="Rechercher un objet…" aria-label="Rechercher un objet" value="${esc(invQuery)}"><select id="inventory-filter" aria-label="Filtrer l’inventaire">${options([['','Tous les objets'],...['Équipement','Arme','Conteneur','Utilitaire','Outil','Consommable'].map(x=>[x,x])],invType)}</select></div><div class="toolbar">${btn('Ajouter un objet','new-item','primary')}${btn('Récupérer du sac','retrieve')}</div><div id="inventory-grid" class="inventory"></div>`);}
function renderInventory(){const s=getState(),items=s.items.filter(i=>(!invType||i.type===invType)&&(i.name+' '+i.description).toLowerCase().includes(invQuery.toLowerCase()));$('#inventory-grid').innerHTML=items.map(i=>`<button class="item-tile ${i.equipped?'equipped':''}" data-cmd="item|${esc(i.id)}" data-detail="item:${esc(i.id)}"><span class="qty">×${i.quantity}</span>${i.attuned?'<span class="link-dot" aria-label="Harmonisé">◇</span>':''}${icon(i.icon)}<b>${esc(i.name)}</b><small>${esc(i.rarity)}${i.equipped?' · porté':''}</small></button>`).join('')||'<p>Aucun objet trouvé.</p>';}
function journal(s){return heading('Les traces du voyage','Ce qui mérite de ne pas être oublié.',btn('+ Note','new-note','primary'))+`<input id="note-search" class="search" placeholder="Rechercher dans le journal…" aria-label="Rechercher dans le journal" value="${esc(noteQuery)}"><select id="category-filter" aria-label="Catégorie de notes">${options([['','Toutes les catégories'],...s.categories.map(c=>[c.id,c.name])],noteCategory)}</select><div class="toolbar">${btn('Catégories','categories')}${btn(trash?'Notes actives':'Corbeille','trash')}${btn('Exporter','export-notes')}</div><div class="notes-list" id="notes-list"></div>`;}
function renderNotes(){const s=getState(),notes=s.notes.filter(n=>!!n.deleted===trash&&(!noteCategory||n.category===noteCategory)&&(n.title+' '+n.body+' '+n.tags).toLowerCase().includes(noteQuery.toLowerCase())).sort((a,b)=>Number(b.favorite)-Number(a.favorite)||b.updatedAt.localeCompare(a.updatedAt));$('#notes-list').innerHTML=notes.map(n=>{const c=s.categories.find(c=>c.id===n.category);return `<button class="note-card" style="--note-color:${c?.color||'#dfbd78'}" data-cmd="note|${esc(n.id)}"><small>${n.favorite?'ÉPINGLÉ · ':''}${esc(c?.name||'Sans catégorie')} · ${esc(n.session||new Date(n.updatedAt).toLocaleDateString('fr-FR'))}</small><h3>${esc(n.title||'Sans titre')}</h3><p>${esc(n.body)}</p><small>${esc(n.tags)}</small></button>`}).join('')||`<div class="empty wide">${icon('journal')}<h3>${trash?'Rien dans la corbeille':'Une nouvelle page'}</h3><p>${trash?'Les notes supprimées pourront être restaurées ici.':'Une rencontre, un lieu, un détail… Gardez-en la trace.'}</p>${trash?'':btn('Écrire une note','new-note','primary')}</div>`;}
function detail(id){const s=getState();let d;if(id.startsWith('attack:')){const a=attackStats(s,id.slice(7));d={name:a.name,icon:a.icon,cost:`${signed(a.bonus)} au toucher · 1d${a.die} ${signed(a.damageMod)} ${a.type}`,text:a.description+'\n\n'+s.details.attack.text,source:'Fiche Karu, calcul depuis les caractéristiques'};}else if(id.startsWith('item:')){const i=s.items.find(x=>x.id===id.slice(5));if(!i)return;d={name:i.name,icon:i.icon,cost:i.rarity,text:i.description,sourceText:i.sourceText,source:'Fiche Karu · objet modifiable dans l’inventaire'};}else d=s.details[id];if(!d)return;show(d.name,`<div class="detail-hero">${icon(d.icon)}<b>${esc(d.cost)}</b></div><div class="detail-copy">${esc(d.text)}</div>${d.extra?`<div class="callout">${esc(d.extra)}</div>`:''}<p class="source">Description jouable : ${esc(d.source)}</p>${d.sourceText?`<details><summary>Texte de la fiche d’origine</summary><p class="source">Transcription conservée. Les corrections de calcul et restrictions figurent au-dessus ; DD 14 devient 15 avec la ceinture, et la CA sans armure vaut 10 + 1 + 3.</p><div class="detail-copy">${esc(d.sourceText)}</div></details>`:''}${!id.includes(':')?btn('Modifier cette description','edit-detail|'+id,'quiet'):''}`,'FICHE DÉTAILLÉE');}
function rollControls(mode=rollMode){return `<label>Mode du jet<select id="roll-mode">${options([['normal','Normal · 1d20'],['adv','Avantage · 2d20, garder le meilleur'],['dis','Désavantage · 2d20, garder le plus faible']],mode)}</select></label><label>Jet manuel (facultatif)<input id="manual-dice" placeholder="Ex. 12 ou 12, 7" inputmode="decimal" autocomplete="off"></label><small>Avec avantage/désavantage : saisir les deux dés. Vide = lancer les dés.</small>`;}
function readRoll(kind,key){rollMode=$('#roll-mode').value;const mode=effectiveMode(getState(),rollMode,kind,key);const text=$('#manual-dice').value.trim();const manual=text?text.split(/[,;\s]+/).map(Number):[];const r=d20(mode.mode,manual);return {...r,reasons:mode.reasons};}
function rollHtml(r,bonus){return `<div class="roll-result"><div class="dice">${r.dice.map(n=>`<span class="die">${n}</span>`).join('')}</div><div class="total">${r.natural+bonus}</div><div class="formula">${r.natural} ${signed(bonus)} = ${r.natural+bonus}${r.reasons?.length?' · '+esc(r.reasons.join(', ')):''}</div></div>`;}
function testRoll(kind,key,toolName,toolAttr){const s=getState();const title=kind==='skill'?SKILLS.find(x=>x[0]===key)[1]:kind==='save'?'Sauvegarde de '+ATTRS[key]:kind==='initiative'?'Initiative':kind==='tool'?toolName:ATTRS[key];const bonus=kind==='skill'?skillBonus(s,key):kind==='save'?saveBonus(s,key):kind==='tool'?mod(s.character.stats[toolAttr])+s.character.proficiency:mod(s.character.stats[key]);show(title,`<p>Modificateur : <b>${signed(bonus)}</b></p>${rollControls()}${kind==='save'&&['str','dex'].includes(key)&&['Étourdi','Paralysé','Inconscient'].some(x=>s.conditions.includes(x))?'<p class="danger-text">État actuel : échec automatique aux sauvegardes de Force/Dextérité. Ne lancez que sur arbitrage du MJ.</p>':''}<div class="sheet-actions">${btn('Lancer le test','do-test','primary')}</div>`,'JET DE D20');$('#sheet-body [data-cmd=do-test]').onclick=()=>{try{const r=readRoll(kind,key);dispatch({type:'roll',message:`${title} : [${r.dice.join(', ')}] → ${r.natural} ${signed(bonus)} = ${r.natural+bonus}.`});render();show(title,rollHtml(r,bonus)+`<p class="muted">Le MJ compare le total à la difficulté. Les 1 et 20 naturels n’imposent pas un échec ou une réussite sur ce test.</p>${btn('Terminé','close','primary')}`,'RÉSULTAT DU JET');}catch(e){fail(e)}};}
function attack(id,source='action',returnConfig=null){const s=getState(),reason=canAttack(s,id,source);if(reason)throw new Error(reason);const a={...attackStats(s,id),...(returnConfig?{name:'Renvoi du projectile',type:returnConfig.damageType||'perforants'}:{})},src={action:'ACTION ATTAQUER',arts:'ACTION BONUS · ARTS MARTIAUX',flurry:'ACTION BONUS · RAFALE',opportunity:'RÉACTION · OPPORTUNITÉ',return:'RENVOI · MÊME RÉACTION'}[source];show(returnConfig?'Renvoi du projectile':a.name,`<div class="detail-hero">${icon(a.icon)}<div><b>${signed(returnConfig?.bonus??a.bonus)} au toucher</b><p>1d${returnConfig?.die??a.die} ${signed(returnConfig?.damageMod??a.damageMod)} ${esc(a.type)}</p></div></div>${field('Cible (facultatif)','attack-target',s.lastHit?.target||'')}${rollControls()}${!a.melee?'<p class="source">Au-delà de 6 m et jusqu’à 18 m : choisir désavantage. Au-delà de 18 m : attaque impossible.</p>':''}<label>Jets de dégâts manuels (facultatif)<input id="manual-damage" placeholder="Ex. 4 (critique : 4, 5)" inputmode="decimal"></label><div class="sheet-actions">${btn('Lancer l’attaque','do-attack','primary')}</div><p class="source">Aucune ressource dépensée avant validation. Fermer annule l’attaque.</p>`,src);
 $('#sheet-body [data-cmd=do-attack]').onclick=()=>{try{const r=readRoll('attack'),target=$('#attack-target').value.trim()||'Cible',bonus=returnConfig?.bonus??a.bonus,dm=returnConfig?.damageMod??a.damageMod,die=returnConfig?.die??a.die,count=r.natural===20?2:1,manual=$('#manual-damage').value.trim();const dd=manual?manual.split(/[,;\s]+/).map(Number):rollDice(count,die).dice;if(dd.length!==count||dd.some(n=>!Number.isInteger(n)||n<1||n>die))throw new Error(`Saisir ${count} dé(s) de dégâts entre 1 et ${die}.`);pending={type:'attack',id,source,damageType:a.type,natural:r.natural,target,damage:Math.max(0,dd.reduce((x,y)=>x+y,0)+dm),rollText:`[${r.dice.join(', ')}] → ${r.natural} ${signed(bonus)} = ${r.natural+bonus}`};const critical=r.natural===20,fumble=r.natural===1;show(a.name,rollHtml(r,bonus)+`<p class="formula">Cible : ${esc(target)}</p>${critical?'<div class="callout">20 naturel · touche critique. Les dés de dégâts sont doublés.</div>':fumble?'<div class="callout">1 naturel · attaque manquée.</div>':'<p>Le MJ confirme si le total atteint la CA de la cible.</p>'}${!fumble?`<div class="muted-box">Dégâts si touche : <b>${pending.damage} ${esc(a.type)}</b><br>[${dd.join(' + ')}] ${signed(dm)}</div>`:''}<div class="sheet-actions">${!critical?btn(fumble?'Valider le raté':'Manqué','resolve-attack|miss','quiet'):''}${!fumble?btn(critical?'Valider le critique':'Touché · appliquer','resolve-attack|hit','primary'):''}</div>`,'CONFIRMATION DE L’ATTAQUE');}catch(e){fail(e)}};
}
function onHit(kind){const s=getState(),h=s.lastHit;if(!h)throw new Error('Aucune touche récente.');if(kind==='stun'&&(!h.melee||h.stunUsed))throw new Error('Frappe étourdissante indisponible.');if(kind==='open'&&(!h.flurry||h.openUsed))throw new Error('Main Ouverte indisponible.');show(kind==='stun'?'Frappe étourdissante':'Main Ouverte',`${field('Cible','effect-target',h.target)}${kind==='open'?`<label>Effet<select id="open-effect">${options([['prone','Renversement · DEX'],['push','Projection de 4,5 m · FOR'],['noReaction','Supprimer les réactions · sans JS']],'prone')}</select></label>`:''}<div class="callout">DD ${derived(s).dc}${kind==='stun'?' · Constitution · coût 1 ki':''}. Le MJ donne le résultat de la sauvegarde.</div><label>Résultat du MJ<select id="save-result">${options([['failure','Échec de la cible'],['success','Réussite de la cible']],'failure')}</select></label><details><summary>Faire le jet de la cible avec son modificateur</summary>${field('Modificateur fourni par le MJ','enemy-mod',0,'number')}${btn('Lancer 1d20 pour la cible','enemy-roll')}<p id="enemy-result"></p></details>${btn('Valider l’effet','apply-effect','primary')}`,'EFFET APRÈS TOUCHE');$('#sheet-body [data-cmd=enemy-roll]').onclick=()=>{const bonus=num('enemy-mod');if(!Number.isFinite(bonus))return;const r=d20();$('#save-result').value=r.natural+bonus>=derived(s).dc?'success':'failure';$('#enemy-result').textContent=`${r.natural} ${signed(bonus)} = ${r.natural+bonus} contre DD ${derived(s).dc}`;};if(kind==='open')$('#open-effect').onchange=()=>{$('#save-result').disabled=$('#open-effect').value==='noReaction';};$('#sheet-body [data-cmd=apply-effect]').onclick=()=>commit({type:kind,target:$('#effect-target').value,effect:$('#open-effect')?.value,result:$('#save-result').value});}
function health(){show('Vitalité',`<div class="grid2">${btn(icon('vitalite')+'<br>Subir des dégâts','keypad|damage','danger')}${btn(icon('vitalite')+'<br>Recevoir des soins','keypad|heal')}${btn(icon('carapace')+'<br>PV temporaires','keypad|temp')}${btn('Ajustement MJ','adjust')}</div><p class="source">Les dégâts consomment d’abord les PV temporaires. Ils ne se cumulent jamais entre eux.</p>`);}
function keypad(kind){let value='0';const titles={damage:'Subir des dégâts',heal:'Recevoir des soins',temp:'PV temporaires'};show(titles[kind],`<div class="key-display" id="key-display" aria-live="polite">0</div>${kind==='damage'?check('Coup critique reçu à 0 PV','critical-damage'):kind==='temp'?'<p>La nouvelle valeur remplace les PV temporaires actuels, sans addition. Vous pouvez conserver l’ancienne valeur en annulant.</p>':''}<div class="keypad">${['1','2','3','4','5','6','7','8','9','C','0','⌫'].map(n=>`<button data-key="${n}" aria-label="${n==='⌫'?'Effacer le dernier chiffre':n==='C'?'Effacer tout':n}">${n}</button>`).join('')}<button class="primary confirm" id="confirm-key">Valider</button></div>`);$('#sheet-body').querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{const k=b.dataset.key;value=k==='C'?'0':k==='⌫'?(value.slice(0,-1)||'0'):(value==='0'?k:(value+k).slice(0,5));$('#key-display').textContent=value;});$('#confirm-key').onclick=()=>commit({type:'hp',kind,amount:Number(value),critical:$('#critical-damage')?.checked});}
function confirmAbility(id,label){const s=getState();const detailKey={windDash:'wind',windDisengage:'wind',exit:'shell'}[id]||id,d=s.details[detailKey];show(d?.name||label||'Action',`${d?`<div class="detail-copy">${esc(d.text)}</div>`:`<p>Utiliser votre action pour ${esc(label||id)}. Le MJ résout les conditions, cibles et éventuels tests.</p>`}<div class="sheet-actions">${btn('Confirmer','confirm-ability','primary')}</div>`);$('#sheet-body [data-cmd=confirm-ability]').onclick=()=>commit({type:'ability',id,label});}
function exitShell(){const s=getState(),d=derived(s);show('Sortir de la carapace',`<p>La sortie coûte une action bonus. Une sortie normale laisse Karu à terre.</p>${check('Utiliser le Pas Immobile (1/repos)','exit-belt',false)}${field('Déplacement immédiat avec ceinture (m)','belt-distance',0,'number',`min="0" max="${d.speed||s.character.baseSpeed+s.character.monkSpeed}" step="0.25"`)}<p class="source">Propriété ${s.resources.belt&&d.belt?'disponible':'indisponible'} : se relever gratuitement puis jusqu’à la moitié de la vitesse hors carapace, sans opportunité.</p>${btn('Sortir','confirm-exit','primary')}`);$('#exit-belt').disabled=!(s.resources.belt&&d.belt);$('#belt-distance').disabled=true;$('#exit-belt').onchange=e=>$('#belt-distance').disabled=!e.target.checked;$('#sheet-body [data-cmd=confirm-exit]').onclick=()=>commit({type:'ability',id:'exit',belt:$('#exit-belt').checked,distance:num('belt-distance')});}
function incoming(kind){const s=getState(),d=s.details[kind==='deflect'?'deflect':kind==='fall'?'fall':'evasion'];show(d.name,`${field('Dégâts avant réduction','incoming',0,'number','min="0"')}${kind==='deflect'?`${field('d10 de réduction manuel (facultatif)','deflect-die','','number','min="1" max="10"')}${check('Attaque d’arme à distance (pas un sort)','weapon-confirm')}${check('Si réduit à 0 : projectile tenable et une main libre','catch-projectile')}`:kind==='evasion'?`${check('Cet effet permet un JS DEX pour moitié','eligible-effect')}<label>Résultat de la sauvegarde<select id="evasion-result"><option value="success">Réussite : aucun dégât</option><option value="failure">Échec : moitié des dégâts</option></select></label>`:''}<div class="callout">${kind==='fall'?'Réduction de '+s.character.level*s.character.rules.fallMultiplier:kind==='deflect'?'Réduction de 1d10 + '+(s.character.level+mod(s.character.stats.dex)):'Les dégâts finaux sont appliqués aux PV temporaires puis aux PV.'}</div>${btn('Résoudre et appliquer','resolve-incoming','primary')}`);$('#sheet-body [data-cmd=resolve-incoming]').onclick=()=>{if(kind==='deflect'&&!$('#weapon-confirm').checked)return fail(new Error('Confirmez le type d’attaque.'));commit({type:kind,incoming:num('incoming'),die:$('#deflect-die')?.value?num('deflect-die'):null,catch:$('#catch-projectile')?.checked,eligible:$('#eligible-effect')?.checked,success:$('#evasion-result')?.value==='success'});};}
function returnProjectile(){const s=getState();show('Renvoi du projectile',`<p>Le projectile attrapé compte comme arme de moine, avec maîtrise. Choisissez les valeurs adaptées à cette arme avec le MJ.</p><div class="grid2">${field('Bonus au toucher','return-bonus',mod(s.character.stats.dex)+s.character.proficiency,'number')}${field('Dé de dégâts (faces)','return-die',s.character.martialDie,'number','min="2" max="100"')}${field('Bonus aux dégâts','return-mod',mod(s.character.stats.dex),'number')}${field('Type de dégâts du projectile','return-type','perforants')}</div><p class="source">Proposition DEX pour un projectile à distance ordinaire. Une arme de jet peut conserver sa caractéristique applicable. Portée 6/18 m ; 1 ki ; même réaction.</p>${btn('Préparer le jet','prepare-return','primary')}${btn('Conserver le projectile sans renvoi','decline-return','quiet')}`);$('#sheet-body [data-cmd=prepare-return]').onclick=()=>{const cfg={bonus:num('return-bonus'),die:num('return-die'),damageMod:num('return-mod'),damageType:$('#return-type').value.trim()||'perforants'};if(!Number.isFinite(cfg.bonus)||!Number.isFinite(cfg.damageMod)||!Number.isInteger(cfg.die)||cfg.die<2||cfg.die>100)return fail(new Error('Dé invalide.'));try{attack('dart','return',cfg)}catch(e){fail(e)}};}
function rest(){const s=getState();show('Un temps de repos',`<label>Type<select id="rest-kind"><option value="short">Repos court · au moins 1 heure</option><option value="long">Repos long · au moins 8 heures</option><option value="dawn">Nouvelle aube uniquement</option></select></label><div id="rest-summary" class="callout"></div><div id="rest-hd">${field('Dés de vie à dépenser','rest-dice',0,'number',`min="0" max="${s.resources.hd}"`)}<small>${s.resources.hd}/${s.character.hitDice} dés disponibles · d${s.character.hitDie} ${signed(mod(s.character.stats.con))} chacun</small></div>${check('Au moins 30 minutes de méditation','rest-meditation',true)}${check('Repos long admissible et nourriture/boisson suffisantes','rest-food',true)}<p class="source">Un repos long ne peut procurer ses bénéfices qu’une fois par 24 heures, avec au moins 1 PV à son début. Les états persistants restent à arbitrer par le MJ.</p>${btn('Appliquer le repos','apply-rest','primary')}`);const summary=()=>{const k=$('#rest-kind').value;$('#rest-summary').textContent=k==='short'?'Ki après méditation, ceinture rechargée ; PV seulement avec les dés de vie.':k==='long'?'PV restaurés, intégrité et ceinture rechargées ; récupération de '+Math.max(1,Math.floor(s.character.hitDice/2))+' dés de vie ; PV temporaires retirés. Calebasse inchangée.':'Purification rechargée. Aucun PV, ki ou autre usage restauré.';$('#rest-hd').hidden=k!=='short';$('#rest-meditation').parentElement.hidden=k==='dawn';$('#rest-food').parentElement.hidden=k!=='long';};$('#rest-kind').onchange=summary;summary();$('#sheet-body [data-cmd=apply-rest]').onclick=()=>{const kind=$('#rest-kind').value;if(kind==='long'&&!$('#rest-food').checked)return fail(new Error('Confirmez l’admissibilité du repos long, ou utilisez l’ajustement MJ.'));commit({type:'rest',kind,hd:num('rest-dice'),meditation:$('#rest-meditation').checked,food:$('#rest-food').checked});};}
function movement(){const s=getState(),d=derived(s);show('Le prochain pas',`<div class="row"><span class="pill">Marche ${d.speed} m</span><span class="pill">Escalade ${d.climb} m</span><span class="pill">Reste ${d.moveLeft} m</span></div>${field('Distance parcourue (m)','move-distance',1.5,'number','min="0" step="0.25"')}${check('Terrain difficile (coût doublé)','difficult-terrain')}<p class="source">Ramper à terre double aussi le coût. Les sauts consomment du déplacement. En escalade sans les chaussons actifs, le coût dépend du terrain et du MJ.</p>${btn('Dépenser le déplacement','apply-move','primary')}${s.conditions.includes('À terre')?btn('Se relever · moitié de la vitesse','stand','quiet'):''}`);$('#sheet-body [data-cmd=apply-move]').onclick=()=>commit({type:'move',amount:num('move-distance'),difficult:$('#difficult-terrain').checked});}
function conditions(){const s=getState();show('États de Karu',`<div class="state-list">${CONDITIONS.map(name=>btn(esc(name),'toggle-condition|'+name,s.conditions.includes(name)?'on':'')).join('')}</div>${field('Niveaux d’épuisement (0–6)','exhaustion',s.resources.exhaustion,'number','min="0" max="6"')}<p class="source">Les états bloquant les actions et les principaux désavantages sont pris en compte. Le MJ tranche les conditions dépendant de la cible (visibilité, charme, peur…). Épuisement 2014 : 1 tests désavantagés ; 2 vitesse moitié ; 3 attaques/JS désavantagés ; 4 PV max moitié ; 5 vitesse 0 ; 6 mort.</p>${btn('Appliquer l’épuisement','set-exhaustion','primary')}`);$('#sheet-body [data-cmd=set-exhaustion]').onclick=()=>commit({type:'adjust',values:{exhaustion:num('exhaustion'),...(num('exhaustion')===6?{dead:true,hp:0}:{})}});}
function adjust(){const s=getState(),r=s.resources;show('Ajustement du MJ',`<p>Correction manuelle explicite. Les valeurs restent bornées par la fiche.</p><div class="grid2">${[['PV','hp'],['PV temporaires','tempHp'],['Ki','ki'],['Dés de vie','hd'],['Réussites de mort','success'],['Échecs de mort','failure']].map(([label,k])=>field(label,'adjust-'+k,r[k],'number','min="0"')).join('')}</div>${check('Intégrité physique disponible','adjust-whole',r.whole)}${check('Pas Immobile disponible','adjust-belt',r.belt)}${check('Purification disponible','adjust-gourd',r.gourd)}${check('Stabilisé','adjust-stable',r.stable)}${check('Mort','adjust-dead',r.dead)}${btn('Enregistrer la correction','save-adjust','primary')}`);$('#sheet-body [data-cmd=save-adjust]').onclick=()=>{const values={};for(const k of ['hp','tempHp','ki','hd','success','failure'])values[k]=num('adjust-'+k);for(const k of ['whole','belt','gourd','stable','dead'])values[k]=$('#adjust-'+k).checked;commit({type:'adjust',values});};}
function itemPanel(id){const i=getState().items.find(x=>x.id===id);if(!i)return;show(i.name,`<div class="detail-hero">${icon(i.icon)}<div><b>${esc(i.rarity)}</b><p>×${i.quantity} · ${esc(i.container)}</p></div></div><div class="detail-copy">${esc(i.description)}</div>${i.sourceText?`<details><summary>Texte complet de la fiche</summary><div class="detail-copy">${esc(i.sourceText)}</div></details>`:''}<div class="pills">${i.equipped?'<span class="pill">Porté</span>':''}${i.attuned?'<span class="pill">Harmonisé</span>':''}</div>${i.notes?`<p>${esc(i.notes)}</p>`:''}<div class="sheet-actions">${btn('Modifier','edit-item|'+id,'primary')}${btn(i.equipped?'Ranger':'Équiper','toggle-equip|'+id)}</div>${i.requiresAttunement?btn(i.attuned?'Rompre l’harmonisation':'Harmoniser','toggle-attune|'+id,'quiet'):''}${i.type==='Consommable'?btn('Utiliser une unité','consume|'+id,'quiet'):''}${i.id==='gourd'?btn('Utiliser la purification','gourd','quiet',!getState().resources.gourd):''}<p class="source">Équiper ou harmoniser reflète une décision de jeu : l’application n’accorde pas d’harmonisation instantanée en combat.</p>`,'INVENTAIRE');}
function itemEditor(id){const s=getState(),i=id?clone(s.items.find(x=>x.id===id)):{id:crypto.randomUUID(),name:'',icon:'inventaire',type:'Utilitaire',description:'',quantity:1,rarity:'Ordinaire',equipped:false,requiresAttunement:false,attuned:false,container:'Sur soi',notes:''};show(id?'Modifier l’objet':'Ajouter un objet',`${field('Nom','item-name',i.name)}<div class="grid2"><label>Type<select id="item-type">${options(['Équipement','Arme','Conteneur','Utilitaire','Outil','Consommable'].map(x=>[x,x]),i.type)}</select></label>${field('Quantité','item-qty',i.quantity,'number','min="0" max="9999"')}</div><label>Icône<select id="item-icon">${options(icons.map(x=>[x,x]),i.icon)}</select></label>${field('Rareté','item-rarity',i.rarity)}${field('Conteneur / emplacement','item-container',i.container)}<label>Description complète<textarea id="item-description">${esc(i.description)}</textarea></label>${check('Équipé / porté','item-equipped',i.equipped)}${check('Nécessite l’harmonisation','item-needs',i.requiresAttunement)}${check('Harmonisé','item-attuned',i.attuned)}${i.effect?field('Bonus mécanique de cet objet','item-bonus',i.bonus||0,'number'):''}<label>Notes<textarea id="item-notes">${esc(i.notes)}</textarea></label>${btn('Enregistrer l’objet','save-item','primary')}<p class="source">Quantité 0 conserve la fiche de l’objet. Les effets mécaniques des trois objets liés sont recalculés depuis leur équipement et harmonisation.</p>`);$('#sheet-body [data-cmd=save-item]').onclick=()=>commit({type:'item',item:{...i,name:$('#item-name').value.trim(),type:$('#item-type').value,quantity:num('item-qty'),icon:$('#item-icon').value,rarity:$('#item-rarity').value,container:$('#item-container').value,description:$('#item-description').value,equipped:$('#item-equipped').checked,requiresAttunement:$('#item-needs').checked,attuned:$('#item-attuned').checked,notes:$('#item-notes').value,...(i.effect?{bonus:num('item-bonus')}:{} )}});}
function noteEditor(id){const s=getState();let n=id?s.notes.find(x=>x.id===id):null;if(!n){n={id:crypto.randomUUID(),title:'',body:'',category:s.categories[0]?.id||'',tags:'',session:'',favorite:false,deleted:false,updatedAt:new Date().toISOString()};updateContent(s=>s.notes.unshift(n));}const nid=n.id;show(n.deleted?'Note dans la corbeille':'Une page du voyage',`${field('Titre','note-title',n.title)}<div class="grid2"><label>Catégorie<select id="note-category">${options([['','Sans catégorie'],...s.categories.map(c=>[c.id,c.name])],n.category)}</select></label>${field('Date de séance','note-session',n.session,'date')}</div><label>Votre note<textarea class="note-editor" id="note-body" placeholder="Ce qui s’est passé, ce qu’il faudra retenir…">${esc(n.body)}</textarea></label>${field('Étiquettes (séparées par des virgules)','note-tags',n.tags)}${check('Épingler cette note','note-favorite',n.favorite)}<p class="source" id="note-save-status">Enregistrement automatique sur cet appareil.</p><div class="sheet-actions">${btn('Terminé','close','primary')}${btn(n.deleted?'Restaurer':'Mettre à la corbeille','delete-note|'+nid,n.deleted?'':'danger')}</div>`,'JOURNAL PERSONNEL');const save=()=>{try{updateContent(state=>{const x=state.notes.find(x=>x.id===nid);Object.assign(x,{title:$('#note-title').value,body:$('#note-body').value,category:$('#note-category').value,session:$('#note-session').value,tags:$('#note-tags').value,favorite:$('#note-favorite').checked,updatedAt:new Date().toISOString()});});$('#note-save-status').textContent=getWarning()||'Enregistré sur cet appareil.';}catch(e){fail(e)}};for(const id of ['note-title','note-body','note-category','note-session','note-tags','note-favorite'])$('#'+id).addEventListener('input',save);}
function categories(){const s=getState();show('Catégories du journal',`<div class="flex-col">${s.categories.map((c,i)=>`<div class="row"><span class="color-line" style="--note-color:${c.color}"></span><b style="flex:1">${esc(c.name)}</b>${btn('↑','category-up|'+c.id,'icon-button',i===0)}${btn('Modifier','category-edit|'+c.id)}</div>`).join('')}</div><hr class="divider">${btn('Nouvelle catégorie','category-edit|new','primary')}`);}
function categoryEditor(id){const existing=getState().categories.find(x=>x.id===id),c=existing||{id:crypto.randomUUID(),name:'',color:'#dfbd78'};show('Catégorie',`${field('Nom','category-name',c.name)}${field('Couleur','category-color',c.color,'color')}${btn('Enregistrer','category-save','primary')}`);$('#sheet-body [data-cmd=category-save]').onclick=()=>{const name=$('#category-name').value.trim();if(!name)return fail(new Error('Nom requis.'));updateContent(s=>{const idx=s.categories.findIndex(x=>x.id===c.id),cat={...c,name,color:$('#category-color').value};if(idx<0)s.categories.push(cat);else s.categories[idx]=cat;});render();categories();};}
function history(){const s=getState();show('Historique des gestes',`<input id="log-search" placeholder="Rechercher un jet ou une action…" aria-label="Rechercher dans l’historique"><div id="log-list"></div>`,'300 DERNIERS ÉVÉNEMENTS');const fill=()=>{const q=$('#log-search').value.toLowerCase();$('#log-list').innerHTML=s.log.filter(x=>x.message.toLowerCase().includes(q)).map(x=>`<div class="log-entry"><small>Tour ${x.turn} · ${new Date(x.at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</small>${esc(x.message)}</div>`).join('')||'<p>Aucun événement.</p>';};$('#log-search').oninput=fill;fill();}
function download(name,text,type='application/json'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function settings(){const s=getState();show('Votre compagnon',`<p class="eyebrow">KARU · VERSION 1.0.0</p><div class="grid2">${btn('Modifier la fiche','character','primary')}${btn('Textes & aptitudes','descriptions')}${btn('Exporter la partie','export')}${btn('Importer une partie','import')}${btn('Sauvegarde précédente','restore','',!hasBackup())}${btn('Ajustement du MJ','adjust')}</div>${check('Lisibilité renforcée','high-contrast',s.settings.contrast)}${check('Réduire les animations','low-motion',s.settings.reduceMotion)}<div class="callout">Sauvegarde automatique sur cet appareil uniquement. Exportez régulièrement votre partie : aucun compte ni synchronisation entre appareils.</div><details><summary>Installation sur iPhone</summary><p>Depuis Safari, ouvrir l’adresse GitHub Pages puis Partager → Sur l’écran d’accueil. Attendre « Hors ligne prêt » lors du premier chargement. Les données de Safari et de l’app installée peuvent être séparées : utiliser l’export/import pour transférer une partie.</p></details><details><summary>Règles, sources et arbitrages</summary><p>Moine 2014 et fiche Karu, avec page 4 complémentaire. DD 15 avec la ceinture ; 14 sans. La calebasse décrit 4 litres purifiables pour 2 litres de contenance : volume à arbitrer, sans deuxième usage automatique.</p><p>Les renvois de projectiles se règlent selon l’arme attrapée. Les états ciblés et les durées manuelles se confirment avec le MJ.</p><p><a href="./REGLES-ET-ARBITRAGES.md" target="_blank" rel="noopener">Lire les règles et arbitrages</a></p></details><details><summary>Édition avancée de toutes les données</summary><p>Permet de modifier descriptions, attaques, bonus, maîtrises et compteurs. Une copie précédente est conservée avant remplacement.</p>${btn('Éditer les données JSON','advanced')}${btn('Exporter la sauvegarde brute','export-raw')}</details>`);$('#high-contrast').onchange=e=>{updateContent(s=>s.settings.contrast=e.target.checked);render();};$('#low-motion').onchange=e=>{updateContent(s=>s.settings.reduceMotion=e.target.checked);render();};}
function characterEditor(){const c=getState().character;show('Fiche de Karu',`${field('Nom','char-name',c.name)}${field('Surnom','char-subtitle',c.subtitle)}<div class="grid2">${Object.entries(ATTRS).map(([k,name])=>field(name,'stat-'+k,c.stats[k],'number','min="1" max="30"')).join('')}${[['Niveau','level'],['Maîtrise','proficiency'],['PV maximum','maxHp'],['Ki maximum','maxKi'],['Nombre de dés de vie','hitDice'],['Dé de vie (faces)','hitDie'],['Dé martial (faces)','martialDie'],['CA naturelle','naturalAc'],['Vitesse de base (m)','baseSpeed'],['Bonus de vitesse (m)','monkSpeed'],['Ajustement attaque','attackAdjustment'],['Ajustement dégâts','damageAdjustment'],['Ajustement CA','acAdjustment'],['Ajustement DD','dcAdjustment']].map(([label,k])=>field(label,'char-'+k,c[k],'number','step="0.5"')).join('')}</div>${check('Porte une armure (désactive les bonus sans armure)','char-armor',c.armor)}${check('Porte un bouclier','char-shield',c.shield)}${check('Encombré : chaussons inactifs','char-encumbered',c.encumbered)}${check('Surface glissante : chaussons inactifs','char-slippery',c.slippery)}${field('Langues','char-languages',c.languages)}<p class="source">Maîtrises, règles et autres descriptions : édition avancée disponible dans les réglages.</p>${btn('Enregistrer la fiche','save-character','primary')}`);$('#sheet-body [data-cmd=save-character]').onclick=()=>{const next=clone(c);next.name=$('#char-name').value.trim();next.subtitle=$('#char-subtitle').value;next.languages=$('#char-languages').value;for(const k of Object.keys(ATTRS))next.stats[k]=num('stat-'+k);for(const k of ['level','proficiency','maxHp','maxKi','hitDice','hitDie','martialDie','naturalAc','baseSpeed','monkSpeed','attackAdjustment','damageAdjustment','acAdjustment','dcAdjustment'])next[k]=num('char-'+k);for(const k of ['armor','shield','encumbered','slippery'])next[k]=$('#char-'+k).checked;commit({type:'configure',character:next});};}
function editDetail(id){const d=getState().details[id];show('Modifier l’aptitude',`${field('Nom','detail-name',d.name)}${field('Coût / déclencheur','detail-cost',d.cost)}<label>Description<textarea id="detail-text" style="min-height:260px">${esc(d.text)}</textarea></label><label>Précisions<textarea id="detail-extra">${esc(d.extra)}</textarea></label>${btn('Enregistrer','save-detail','primary')}<p class="source">Modifier le texte ne modifie pas automatiquement la mécanique. Les paramètres chiffrés se trouvent dans la fiche et les données avancées.</p>`);$('#sheet-body [data-cmd=save-detail]').onclick=()=>{updateContent(s=>Object.assign(s.details[id],{name:$('#detail-name').value,cost:$('#detail-cost').value,text:$('#detail-text').value,extra:$('#detail-extra').value,source:'Description personnalisée par le joueur / MJ'}));close();render();toast('Description enregistrée.');};}
function advanced(){show('Toutes les données',`<p>Modifier uniquement les champs souhaités. Le JSON doit rester valide ; les bornes et champs obligatoires seront vérifiés.</p><label>Données de la partie<textarea id="advanced-json" style="min-height:50dvh;font-family:monospace">${esc(JSON.stringify(getState(),null,2))}</textarea></label>${btn('Vérifier avant remplacement','check-json','primary')}`);$('#sheet-body [data-cmd=check-json]').onclick=()=>{try{const next=importData($('#advanced-json').value);previewImport(next)}catch(e){fail(e)}};}
function previewImport(next){show('Vérifier le remplacement',`<p>Remplacer la partie locale par :</p><div class="muted-box"><b>${esc(next.character.name)}</b> · niveau ${next.character.level}<br>${next.resources.hp} PV · ${next.resources.ki} ki<br>${next.items.length} objets · ${next.notes.length} notes<br>Tour ${next.turn.number}</div><p>Une copie de la sauvegarde actuelle sera conservée. Aucun remplacement n’a encore eu lieu.</p><div class="sheet-actions">${btn('Annuler','close')}${btn('Remplacer la partie','confirm-import','primary')}</div>`);$('#sheet-body [data-cmd=confirm-import]').onclick=()=>{try{replaceState(next);close();render();toast('Partie importée. La précédente reste récupérable.')}catch(e){fail(e)}};}
$('#import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>6000000)throw new Error('Fichier trop volumineux.');previewImport(importData(await f.text()));}catch(err){toast('Import refusé : '+err.message)}e.target.value='';};
function death(){show('Jet de mort',`${rollControls('normal')}<p>10 ou plus : réussite. 1 naturel : deux échecs. 20 naturel : 1 PV. Trois réussites stabilisent, trois échecs entraînent la mort.</p>${btn('Lancer le jet de mort','roll-death','primary')}`);$('#sheet-body [data-cmd=roll-death]').onclick=()=>{try{const r=readRoll('death');commit({type:'death',natural:r.natural})}catch(e){fail(e)}};}
function coins(){const s=getState();show('La bourse',`<div class="grid2">${Object.entries(s.coins).map(([k,v])=>field(k.toUpperCase(),'coin-'+k,v,'number','min="0"')).join('')}</div>${btn('Enregistrer','save-coins','primary')}`);$('#sheet-body [data-cmd=save-coins]').onclick=()=>commit({type:'coins',coins:Object.fromEntries(Object.keys(s.coins).map(k=>[k,num('coin-'+k)]))});}
function freeDice(){show('Dés libres',`<div class="grid2">${field('Nombre de dés','free-count',1,'number','min="1" max="100"')}${field('Nombre de faces','free-sides',6,'number','min="2" max="1000"')}${field('Modificateur','free-mod',0,'number')}</div>${btn('Lancer','free-roll','primary')}`);$('#sheet-body [data-cmd=free-roll]').onclick=()=>{try{const count=num('free-count'),sides=num('free-sides'),m=num('free-mod');if(!Number.isFinite(m))throw new Error('Modificateur invalide.');const r=rollDice(count,sides),msg=`${count}d${sides} ${signed(m)} : [${r.dice.join(', ')}] = ${r.total+m}`;commit({type:'roll',message:msg});}catch(e){fail(e)}};}
function route(command){const [cmd,a,b]=command.split('|'),s=getState();switch(cmd){
 case 'nav':view=a;close();render();window.scrollTo({top:0,behavior:'instant'});break;
 case 'close':close();render();break;
 case 'combat-tab':combatTab=a;render();break;
 case 'social-tab':socialTab=a;render();break;
 case 'detail':detail(a);break;
 case 'attack':attack(a,b);break;
 case 'resolve-attack':if(pending){const event={...pending,hit:a==='hit'};if(commit(event))pending=null;}break;
 case 'stun':onHit('stun');break;case 'open':onHit('open');break;
 case 'health':health();break;case 'keypad':keypad(a);break;
 case 'undo':toast(undoLast());render();break;
 case 'end-turn':show('Terminer votre tour',`<p>Les attaques et frappes restantes seront abandonnées. La réaction reste dans son état actuel.</p>${btn('Terminer le tour','confirm-end','primary')}`);break;
 case 'confirm-end':commit({type:'endTurn'});break;
 case 'start-turn':commit({type:'startTurn'});break;
 case 'forfeit':commit({type:'finishAttacks'});break;
 case 'ability':confirmAbility(a);break;
 case 'common':confirmAbility(a,b);break;
 case 'wind':show('Déplacement aérien',`<p>Une action bonus et ${s.character.rules.windCost} ki. Les sauts sont doublés pour le tour.</p><div class="grid2">${btn('Foncer','ability|windDash','primary')}${btn('Se désengager','ability|windDisengage')}</div>`);break;
 case 'exit':exitShell();break;
 case 'still':show('Quiétude de l’esprit',`<p>Le MJ confirme que l’effet permet à Karu de choisir cette action.</p><div class="grid2">${['Charmé','Effrayé'].map(c=>btn('Terminer : '+c,'end-condition|'+c,'',!s.conditions.includes(c))).join('')}</div>`);break;
 case 'end-condition':commit({type:'ability',id:'still',condition:a});break;
 case 'deflect':incoming('deflect');break;case 'fall':incoming('fall');break;case 'evasion':incoming('evasion');break;
 case 'return':returnProjectile();break;case 'decline-return':commit({type:'declineReturn'});break;
 case 'opportunity':show('Attaque d’opportunité',`<p>Confirmer le déclencheur et la visibilité avec le MJ. Une seule attaque de corps à corps.</p>${Object.entries(s.attacks).filter(([,v])=>v.melee).map(([id,a])=>card(a.name,'Utilise la réaction',a.icon,'attack|'+id+'|opportunity','attack:'+id)).join('')}`);break;
 case 'roll':testRoll(a,b);break;
 case 'tool':{const name=s.character.tools[Number(a)];show(name,`<label>Caractéristique du test<select id="tool-attr">${options(Object.entries(ATTRS),'wis')}</select></label><p>Le bonus de maîtrise est ajouté une seule fois.</p>${btn('Préparer le test','prepare-tool','primary')}`);$('#sheet-body [data-cmd=prepare-tool]').onclick=()=>testRoll('tool','',name,$('#tool-attr').value);break;}
 case 'free-dice':freeDice();break;case 'death':death();break;case 'stabilize':commit({type:'stabilize'});break;
 case 'movement':movement();break;case 'stand':commit({type:'stand'});break;
 case 'rest':rest();break;case 'conditions':conditions();break;
 case 'toggle-condition':if(commit({type:'condition',name:a,active:!s.conditions.includes(a)},{stay:true}))conditions();break;
 case 'remove-effect':commit({type:'removeEffect',id:a});break;
 case 'adjust':adjust();break;
 case 'resources':show('Ressources de Karu',`<div class="muted-box">Ki : ${s.resources.ki}/${s.character.maxKi}<br>Dés de vie : ${s.resources.hd}/${s.character.hitDice}<br>Intégrité physique : ${s.resources.whole?'disponible':'utilisée'}<br>Pas Immobile : ${s.resources.belt?'disponible':'utilisé'}<br>Calebasse : ${s.resources.gourd?'disponible':'utilisée'}</div><div class="sheet-actions">${btn('Repos','rest','primary')}${btn('Ajuster','adjust')}</div>`);break;
 case 'item':itemPanel(a);break;case 'new-item':itemEditor();break;case 'edit-item':itemEditor(a);break;
 case 'toggle-equip':case 'toggle-attune':{const it=clone(s.items.find(x=>x.id===a)),key=cmd==='toggle-equip'?'equipped':'attuned';it[key]=!it[key];if(commit({type:'item',item:it},{stay:true}))itemPanel(a);break;}
 case 'consume':show('Utiliser cet objet',`<p>Retirer une unité de ${esc(s.items.find(x=>x.id===a)?.name)}. L’effet et le coût en action se résolvent avec le MJ.</p>${btn('Utiliser une unité','confirm-consume|'+a,'primary')}`);break;
 case 'confirm-consume':commit({type:'consume',id:a});break;
 case 'retrieve':show('Récupérer un objet',`<p>Récupérer un objet dans le Sac sans fond utilise votre action.</p>${btn('Utiliser l’action','confirm-retrieve','primary')}`);break;
 case 'confirm-retrieve':commit({type:'retrieve'});break;
 case 'gourd':show('Purifier de l’eau',`<p>Confirmer que la calebasse est vide avant d’y verser l’eau. La fiche indique 4 L purifiables mais 2 L de contenance : le MJ valide le volume. Un seul usage par aube.</p>${btn('Utiliser la purification','confirm-gourd','primary')}`);break;
 case 'confirm-gourd':commit({type:'gourd'});break;
 case 'coins':coins();break;
 case 'new-note':noteEditor();break;case 'note':noteEditor(a);break;
 case 'delete-note':updateContent(s=>{const n=s.notes.find(x=>x.id===a);n.deleted=!n.deleted;n.updatedAt=new Date().toISOString();});close();render();toast('Journal mis à jour.');break;
 case 'trash':trash=!trash;render();break;case 'categories':categories();break;case 'category-edit':categoryEditor(a);break;
 case 'category-up':updateContent(s=>{const idx=s.categories.findIndex(x=>x.id===a);if(idx>0)[s.categories[idx-1],s.categories[idx]]=[s.categories[idx],s.categories[idx-1]]});render();categories();break;
 case 'export-notes':download('Karu-Journal.md','# Journal de Karu\n\n'+s.notes.filter(n=>!n.deleted).map(n=>`## ${n.title||'Sans titre'}\n\n${s.categories.find(c=>c.id===n.category)?.name||'Sans catégorie'} · ${n.session||''}\n\n${n.body}\n\nÉtiquettes : ${n.tags}`).join('\n\n---\n\n'),'text/markdown;charset=utf-8');break;
 case 'history':history();break;case 'settings':settings();break;case 'character':characterEditor();break;
 case 'descriptions':show('Textes des aptitudes',Object.entries(s.details).map(([id,d])=>card(d.name,d.cost,d.icon,'edit-detail|'+id,id)).join(''));break;
 case 'edit-detail':editDetail(a);break;
 case 'advanced':advanced();break;
 case 'export':download('Karu-Partie-'+new Date().toISOString().slice(0,10)+'.json',exportData(s));toast('Export de la partie préparé.');break;
 case 'export-raw':download('Karu-Sauvegarde-Brute.json',rawSave());break;
 case 'import':$('#import-file').click();break;
 case 'restore':show('Sauvegarde précédente',`<p>Revenir à la copie conservée avant le dernier remplacement. La partie actuelle sera conservée à son tour.</p>${btn('Restaurer cette copie','confirm-restore','primary')}`);break;
 case 'confirm-restore':restoreBackup();close();render();toast('Copie précédente restaurée.');break;
 }}
bindLongPress(document,el=>{try{detail(el.dataset.detail)}catch(err){fail(err)}});
document.addEventListener('click',e=>{const button=e.target.closest('[data-cmd]');if(!button||button.disabled)return;try{route(button.dataset.cmd)}catch(err){fail(err)}});
render();
if('serviceWorker' in navigator&&location.protocol!=='file:'){
 navigator.serviceWorker.register('./sw.js').then(async registration=>{await navigator.serviceWorker.ready;offlineReady=true;render();if(registration.waiting)toast('Mise à jour prête : fermez puis rouvrez le compagnon.');}).catch(()=>{offlineReady=false;toast('Cache hors ligne indisponible. La sauvegarde locale reste indépendante.');});
}
window.addEventListener('online',()=>render());window.addEventListener('offline',()=>render());
