import {SOURCE_DETAILS,SOURCE_ITEMS} from './source-texts.js';
export const VERSION = 1;
export const ATTRS = {str:'Force',dex:'Dextérité',con:'Constitution',int:'Intelligence',wis:'Sagesse',cha:'Charisme'};
export const SKILLS = [
['acrobaties','Acrobaties','dex',0],['arcanes','Arcanes','int',0],['athletisme','Athlétisme','str',1],['discretion','Discrétion','dex',0],['dressage','Dressage','wis',0],['escamotage','Escamotage','dex',0],['histoire','Histoire','int',0],['intimidation','Intimidation','cha',0],['intuition','Intuition','wis',1],['investigation','Investigation','int',0],['medecine','Médecine','wis',1],['nature','Nature','int',0],['perception','Perception','wis',0],['persuasion','Persuasion','cha',0],['religion','Religion','int',1],['representation','Représentation','cha',0],['survie','Survie','wis',1],['tromperie','Tromperie','cha',0]];
const detail=(name,icon,cost,text,source='Fiche Karu et page 4 complémentaire',extra='')=>({name,icon,cost,text,source,extra});
export const DETAILS={
 attack:detail('Attaque supplémentaire','baton','1 action · 2 attaques','Lorsque Karu utilise l’action Attaquer, il peut effectuer deux attaques au lieu d’une. Chaque attaque se résout séparément. Il peut se déplacer entre elles. Une attaque d’opportunité ne bénéficie pas de cette deuxième attaque.'),
 arts:detail('Arts martiaux','poing','Action bonus · sans ki','Sans armure ni bouclier, et à mains nues ou en maniant uniquement des armes de moine, Karu peut utiliser la Dextérité à la place de la Force et le dé d’arts martiaux pour ses frappes et armes de moine. Après l’action Attaquer avec une frappe à mains nues ou une arme de moine, il peut effectuer une frappe à mains nues en action bonus. Karu privilégie sa Force. Une fléchette n’est pas une arme de moine dans ces règles.'),
 flurry:detail('Rafale de coups','poing','1 ki · action bonus','Immédiatement après l’action Attaquer à son tour, Karu peut dépenser 1 ki pour deux frappes à mains nues en une seule action bonus. Elle remplace la frappe bonus des Arts martiaux. Chacune des touches peut déclencher une Technique de la Main Ouverte. Le ki est dépensé à la validation de la première attaque.'),
 patient:detail('Défense patiente','meditation','1 ki · action bonus','Karu utilise Esquiver. Jusqu’au début de son prochain tour, les attaques contre lui ont le désavantage s’il voit l’attaquant, et ses sauvegardes de Dextérité ont l’avantage. Le bénéfice cesse s’il est neutralisé ou si sa vitesse tombe à 0. Les conditions propres à l’attaquant restent à vérifier par le MJ.'),
 wind:detail('Déplacement aérien','deplacement','1 ki · action bonus','Choisir Foncer ou Se désengager. Foncer accorde du déplacement supplémentaire égal à la vitesse actuelle ; Se désengager évite les attaques d’opportunité pour le reste du tour. La distance de saut est doublée ce tour, sans supprimer le coût de déplacement du saut.'),
 stun:detail('Frappe étourdissante','ki','1 ki · après une touche au corps à corps','Après avoir touché une créature avec une attaque d’arme au corps à corps, y compris une frappe à mains nues, Karu peut dépenser 1 ki. La cible fait une sauvegarde de Constitution contre le DD de ki. En cas d’échec, elle est étourdie jusqu’à la fin du prochain tour de Karu. L’application laisse le MJ déterminer le résultat de la sauvegarde.'),
 open:detail('Technique de la Main Ouverte','main-ouverte','Après une touche de Rafale · aucun ki supplémentaire','À chaque touche de Rafale de coups, choisir un seul effet : Renversement, sauvegarde de Dextérité ou cible à terre ; Projection, sauvegarde de Force ou repoussement jusqu’à 4,5 m ; Suppression des réactions, sans sauvegarde, jusqu’à la fin du prochain tour de Karu. Le DD vaut 15 avec la ceinture active, 14 sans elle.'),
 deflect:detail('Parade de projectiles','reaction','Réaction · renvoi facultatif : 1 ki','Déclencheur : une attaque d’arme à distance touche Karu. Réduire les dégâts de 1d10 + modificateur de Dextérité + niveau de moine (1d10 + 8). Si les dégâts sont réduits à 0, il peut attraper le projectile s’il tient dans une main et si une main est libre. Dépenser alors 1 ki permet un renvoi immédiat dans la même réaction, à 6/18 m, avec maîtrise ; le projectile compte comme arme de moine. Une attaque de sort à distance n’est pas éligible.','Fiche, page 4 ; règles de base D&D 2014','Le renvoi dépend de l’arme ou munition attrapée : choisir le bonus et les dégâts avant le jet. Proposition initiale : DEX + maîtrise, 1d6 + DEX ; à ajuster si le projectile utilise une autre caractéristique ou un dé supérieur.'),
 fall:detail('Chute ralentie','deplacement','Réaction','Lorsque Karu tombe, il peut utiliser sa réaction pour réduire ses dégâts de chute de cinq fois son niveau de moine, soit 35. Une réduction ne produit jamais de dégâts négatifs.'),
 evasion:detail('Esquive instinctive','meditation','Passif · effet admissible','Lorsqu’un effet permet une sauvegarde de Dextérité pour ne subir que la moitié des dégâts, Karu ne subit aucun dégât sur une réussite et la moitié sur un échec. Les moitiés sont arrondies à l’inférieur. Ne pas appliquer à un autre type de sauvegarde ou à un effet qui ne propose pas la moitié des dégâts.'),
 still:detail('Quiétude de l’esprit','meditation','1 action','Karu peut mettre fin à un effet qui le rend charmé ou effrayé. Il doit pouvoir utiliser son action : une obligation de comportement imposée par l’effet peut empêcher ce choix. Le MJ confirme cette possibilité.'),
 whole:detail('Intégrité physique','vitalite','1 action · 1/repos long','Karu récupère trois fois son niveau de moine en PV, soit 21 PV. Les soins sont plafonnés au maximum. Cette aptitude se recharge à la fin d’un repos long.'),
 shell:detail('Défense de carapace','carapace','1 action pour entrer · action bonus pour sortir','Karu rentre dans sa carapace : +4 à la CA, avantages aux sauvegardes de Force et Constitution, à terre, vitesse 0 sans possibilité d’augmentation, désavantage aux sauvegardes de Dextérité, aucune réaction. La seule action possible est de sortir de la carapace en action bonus. Sortir normalement ne relève pas automatiquement Karu. La propriété de la ceinture peut le relever sans déplacement et lui offrir un déplacement immédiat.'),
 belt:detail('Pas Immobile','ceinture','Facultatif à la sortie · 1/repos court ou long','En sortant de Défense de carapace, Karu peut se relever sans dépenser de déplacement puis se déplacer immédiatement jusqu’à la moitié de sa vitesse sans provoquer d’attaque d’opportunité. La sortie utilise toujours son action bonus. Cet usage est distinct du ki et n’est pas nécessaire pour une sortie normale.'),
 opportunity:detail('Attaque d’opportunité','reaction','Réaction · 1 attaque','Quand une créature hostile visible quitte l’allonge de Karu sans éviter ce déclencheur, il peut effectuer une attaque de corps à corps juste avant qu’elle ne quitte cette allonge. Une seule attaque, pas l’action Attaquer. La réaction se récupère au début du prochain tour de Karu.'),
 ki:detail('Ki','ki','7 points · repos court ou long','Les points dépensés se récupèrent à la fin d’un repos court ou long comprenant au moins 30 minutes de méditation. Le DD de ki est 8 + maîtrise + Sagesse, avec +1 si la Ceinture du Pas Immobile est active sans armure ni bouclier.'),
 empowered:detail('Frappes de ki','poing','Passif','Les frappes à mains nues de Karu sont considérées comme magiques pour surmonter les résistances et immunités aux attaques et dégâts non magiques. Cela n’enchante pas son bâton ou ses fléchettes et n’ajoute pas de dégâts.'),
 breath:detail('Apnée','meditation','Passif','Karu peut retenir sa respiration pendant une heure. Il ne peut pas respirer sous l’eau grâce à cette seule aptitude.'),
 natural:detail('Armure naturelle','carapace','Passif','La carapace fournit une CA de base de 17. La Défense sans armure donne une autre formule : 10 + DEX + SAG = 14. Ne pas cumuler ces formules. Avec les brassards actifs, Karu utilise 17 + 2 = 19, ou 23 dans sa carapace.'),
 movement:detail('Déplacement sans armure','deplacement','Passif','Sans armure ni bouclier, le déplacement de base de 9 m augmente de 4,5 m au niveau 7. Total : 13,5 m. Les Chaussons d’araignée confèrent une vitesse d’escalade égale à cette vitesse quand leurs conditions sont remplies. Karu n’a pas encore la course sur les surfaces et liquides du niveau 9.'),
 survival:detail('Instinct de survie','social','Passif','Karu maîtrise Survie. Son historique d’ermite lui apporte Médecine, Religion et le matériel d’herboriste. Il maîtrise également le matériel de calligraphie. Langues : commun, aquatique, céleste.'),
};
const item=(id,name,icon,type,description,more={})=>({id,name,icon,type,description,quantity:1,rarity:'Ordinaire',equipped:false,requiresAttunement:false,attuned:false,container:'Sur soi',notes:'',...more});
export const ITEMS=[
 item('belt','Ceinture du Pas Immobile','ceinture','Équipement','Ceinture gris-vert renforcée de sept plaques de jade. Sans armure ni bouclier : +1 au DD des aptitudes de moine utilisant le ki. À la sortie de la carapace, possibilité de se relever sans mouvement et de se déplacer immédiatement de la moitié de sa vitesse sans attaque d’opportunité, une fois par repos court ou long. Harmonisation par un moine.',{rarity:'Rare · maison',equipped:true,requiresAttunement:true,attuned:true,effect:'belt',bonus:1}),
 item('bracers','Brassards de défense','brassards','Équipement','Tant que ces brassards sont portés sans armure ni bouclier, la CA augmente de 2. Harmonisation requise. CA habituelle de Karu : 19 ; carapace : 23.',{rarity:'Rare',equipped:true,requiresAttunement:true,attuned:true,effect:'bracers',bonus:2}),
 item('slippers','Chaussons d’araignée','chaussons','Équipement','Marcher sur les surfaces verticales et les plafonds, les mains libres, avec une vitesse d’escalade égale à la vitesse de marche. Il faut être chaussé et ne pas être encombré. Les surfaces glissantes (glace, huile…) ne sont pas praticables de cette manière. Harmonisation requise.',{rarity:'Peu commun',equipped:true,requiresAttunement:true,attuned:true,effect:'slippers'}),
 item('bag','Sac sans fond','inventaire','Conteneur','Contient jusqu’à 250 kg et 1,8 m³ selon la fiche, en pesant environ 7 kg. Récupérer un objet demande une action. Il renferme herbes, notes, couvertures et matériel. Ne pas placer un espace extradimensionnel dans un autre : interaction dangereuse à résoudre par le MJ.',{rarity:'Peu commun',equipped:true}),
 item('gourd','Calebasse du Chemin Tranquille','calebasse','Utilitaire','Une fois par aube, si elle est vide, purifie jusqu’à 4 litres d’eau non magique : eau potable, impuretés ordinaires retirées. Transforme des herbes en infusion chaude en une minute, sans feu ni eau bouillante. Préserve les plantes et préparations non magiques du moisissement et de la perte de fraîcheur. Contenance indiquée : environ 2 litres. Incohérence 4 L / 2 L à arbitrer par le MJ, sans accorder un deuxième usage.',{rarity:'Commun · maison'}),
 item('staff','Bâton de marche','baton','Arme','Arme de moine : 1d6 + Force à une main, 1d8 + Force à deux mains, contondants.',{equipped:true}),
 item('darts','Fléchettes','flechettes','Arme','Armes de jet, finesse, portée 6/18 m, 1d4 + Force ou Dextérité perforants. Karu utilise la Force.',{quantity:10}),
 item('pack','Sac d’explorateur','inventaire','Conteneur','Équipement de voyage de la fiche. Détailler le contenu validé avec le MJ.'),
 item('herbs-kit','Matériel d’herboriste','repos','Outil','Outil maîtrisé. La caractéristique du test dépend de la tâche et du MJ.',{container:'Sac sans fond'}),
 item('ink-kit','Matériel de calligraphie','journal','Outil','Outil maîtrisé. Choisir la caractéristique selon la tâche.',{container:'Sac sans fond'}),
 item('herbs','Plantes séchées','repos','Utilitaire','Herbes et plantes récoltées par Karu.',{container:'Sac sans fond'}),
 item('notes','Notes de méditation','journal','Utilitaire','Enseignements et observations.',{container:'Sac sans fond'}),
 item('blanket','Couverture simple','inventaire','Utilitaire','Une couverture de voyage.',{container:'Sac sans fond'}),
 item('clothes','Vêtements usés','meditation','Équipement','Étoffes de moine, sans armure.',{equipped:true})
];
export const ATTACKS={staff:{name:'Bâton · une main',icon:'baton',die:6,type:'contondants',melee:true,monk:true,attr:'str',description:'Allonge 1,5 m. Arme de moine, tenue à une main.'},staff2:{name:'Bâton · deux mains',icon:'baton',die:8,type:'contondants',melee:true,monk:true,attr:'str',description:'Allonge 1,5 m. Nécessite deux mains au moment de frapper.'},unarmed:{name:'Frappe à mains nues',icon:'poing',die:6,type:'contondants',melee:true,monk:true,unarmed:true,attr:'str',description:'Allonge 1,5 m. Frappes de ki : magique contre résistances et immunités.'},claws:{name:'Griffes',icon:'griffes',die:6,type:'tranchants',melee:true,monk:true,unarmed:true,attr:'str',description:'Allonge 1,5 m. Frappe à mains nues avec les griffes, selon la fiche.'},dart:{name:'Fléchette',icon:'flechettes',die:4,type:'perforants',melee:false,monk:false,attr:'str',description:'Portée 6/18 m. Désavantage au-delà de 6 m ; impossible au-delà de 18 m. Dépense une fléchette.'}};
export const CONDITIONS=['À terre','Charmé','Effrayé','Agrippé','Entravé','Aveuglé','Assourdi','Empoisonné','Étourdi','Paralysé','Inconscient','Neutralisé','Invisible'];
for(const [id,text] of Object.entries(SOURCE_DETAILS))if(DETAILS[id])DETAILS[id].sourceText=text;
for(const it of ITEMS)if(SOURCE_ITEMS[it.id])it.sourceText=SOURCE_ITEMS[it.id];
export function initial(){return {
 schema:VERSION,character:{name:'Karu',subtitle:'Grand-Père Coquille',level:7,stats:{str:18,dex:12,con:14,int:8,wis:16,cha:8},proficiency:3,maxHp:52,maxKi:7,hitDice:7,hitDie:8,naturalAc:17,baseSpeed:9,monkSpeed:4.5,martialDie:6,attackAdjustment:0,damageAdjustment:0,acAdjustment:0,dcAdjustment:0,saves:{str:1,dex:1,con:0,int:0,wis:0,cha:0},saveAdjustments:{},skills:Object.fromEntries(SKILLS.map(([id,,,p])=>[id,{proficiency:p,adjustment:0}])),languages:'Commun, aquatique, céleste',tools:['Herboriste','Calligraphie'],rules:{shellBonus:4,flurryCost:1,patientCost:1,windCost:1,stunCost:1,returnCost:1,wholeMultiplier:3,fallMultiplier:5},armor:false,shield:false,encumbered:false,slippery:false},
 resources:{hp:52,tempHp:0,ki:7,hd:7,whole:true,belt:true,gourd:true,success:0,failure:0,stable:false,dead:false,exhaustion:0},
 turn:{number:1,phase:'active',action:false,bonus:false,reaction:false,attacksLeft:0,attackTaken:false,martialQualified:false,flurryLeft:0,moveSpent:0,dashes:0,flurryWindow:false},
 shell:false,conditions:[],effects:[],lastHit:null,returnReady:false,items:structuredClone(ITEMS),attacks:structuredClone(ATTACKS),details:structuredClone(DETAILS),coins:{pc:0,pa:0,pe:0,po:0,pp:0},notes:[],categories:[{id:'quests',name:'Quêtes',color:'#dfbd78'},{id:'people',name:'Personnages',color:'#9fc7b4'},{id:'places',name:'Lieux',color:'#95b4d4'},{id:'clues',name:'Indices',color:'#c8a3c3'},{id:'memories',name:'Souvenirs',color:'#d6aa85'}],log:[],settings:{contrast:false,reduceMotion:false},updatedAt:null
};}
